# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-20 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171019_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses/%Y/%m', verbose_name='\u6559\u5e08\u5934\u50cf'),
        ),
    ]
