# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-22 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20171016_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '\u8bfe\u7a0b'), (3, '\u6559\u5e08'), (2, '\u673a\u6784')], verbose_name='\u6536\u85cf\u7c7b\u578b'),
        ),
    ]
