# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_video_learn_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='coures',
            new_name='course',
        ),
    ]
