# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20171023_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u4e3b\u8bb2\u8001\u5e08'),
        ),
    ]
