# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-23 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, max_length=30, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Teacher', verbose_name='\u4e3b\u8bb2\u8001\u5e08'),
        ),
    ]
