# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20171023_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u4e3a\u8f6e\u64ad\u56fe'),
        ),
    ]
